version: "3.9"

services:
  api:
    build: .
    command: npm start
    restart: always
  caddy:
    image: caddy:2.1.1
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp

volumes:
  caddy_data:
  caddy_config: