FROM node:14.16.1-slim
WORKDIR /app
RUN npm i -g pnpm serve
COPY ./pnpm-lock.yaml ./package.json ./
RUN --mount=type=cache,target=/app/pnpm-store \
    pnpm config set store-dir /app/pnpm-store && \
    pnpm install
COPY ./ ./
RUN pnpm build
CMD serve -s build